# notes:
# - When running against the image build with buildx it seems that docker can't find the image:
#     https://github.com/wagoodman/anchore-engine/runs/3633243352?check_suite_focus=true
#   there was a helpful warning message for me:
#   time="2021-09-17T14:30:54Z" level=warning msg="No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load"

# notes:
# - should show syft logs by default (-v or -vv), there are env vars for this too... maybe expose this as a configurable?
# - defaults to hard coded docker: even though this may not be true (don't see a great way around this except for allowing syft to guess)
# - sub actions are slick! we should have more examples around them
# - given there is a download subaction, shouldn't we allow for controlling the syft version?
# - the attach sub action is great, in the future we could consider this for a cosign integration
# - "option" sbom-artifact-match is not working : Unexpected input(s) 'sbom-artifact-match', valid inputs are ['path', 'image', 'github-token', 'artifact-name']


name: "Release"
on:
  release:
  push:
    # take no actions on push to any branch...
    branches-ignore:
      - "**"
    # ... only act on release tags
    tags:
      - "v*"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      ###########################

      # - uses: anchore/sbom-action/download@main
      #   id: syft

      # - name: Run syft manually
      #   run: |
      #     ${{ steps.syft.outputs.cmd }} power-user -vv dir:./
      
      ###########################

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: false
      #     load: true
      #     tags: localhost/anchore-engine:latest
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      #     build-args: |
      #       CLI_COMMIT=17164d36f833341390ba4ec4a187c9f3a97b3540

      # - name: Show image
      #   run: |
      #     docker images

      # # This ugly bit is necessary if you don't want your cache to grow forever
      # # till it hits GitHub's limit of 5GB.
      # # Temp fix
      # # https://github.com/docker/build-push-action/issues/252
      # # https://github.com/moby/buildkit/issues/1896
      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache


      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true

      - uses: anchore/sbom-action@main
        with:
          artifact-name: sbom.spdx
          # image: localhost/anchore-engine:latest

      - uses: anchore/sbom-action/attach@main
        with:
          sbom-artifact-match: ".*\\.spdx$"